import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Strong} from "@/components/typography";
import sideData from "@/lib/site-data";
import {cn} from "@/lib/utils";
import Link from "next/link";
import type {PropsWithChildren} from "react";

const GEIST_SANS = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const GEIST_MONO = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let fullYear = new Date().getFullYear();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GEIST_SANS.variable} ${GEIST_MONO.variable} antialiased`}
      >
        <header className="mb-5">
          <Wrapper className="flex items-center justify-between">
            <Strong>
              <Link href="/" className="hover:underline">
                {sideData.siteName}
              </Link>
            </Strong>
          </Wrapper>
        </header>
        {/* 16rem */}
        <main className="flex min-h-[calc(100vh-16rem)] flex-col items-center justify-center gap-5">
          {children}
        </main>
        <footer>
          <Wrapper>
            <small>All rights reserved &copy; {fullYear}</small>
            <br />
            <small>
              Built with{" "}
              {sideData.tools.map((x) => (
                <span key={x} className="mx-[1px] inline-block font-semibold">
                  {x}
                </span>
              ))}
            </small>
          </Wrapper>
        </footer>
      </body>
    </html>
  );
}

function Wrapper({
  children,
  className,
}: PropsWithChildren<{
  className?: string;
}>) {
  return (
    <div className={cn("mx-auto h-32 max-w-7xl", className)}>{children}</div>
  );
}
